### ISSUE TITLE
[Feature Request]: Chat message hint about locking

### ISSUE THREAD

**Issue by ilfarpro** [spnda/BlockProt#120]
### Feature description

New players don't know that there are ability to lock their chests, etc. So it would be great each time player interacts with lockable thing it shows a notification that he can lock it and how to do this. I think it's essential

**Comment by spnda** [comment]
Do you imagine this to be a one time message when the player first interacts with a block? I think showing a message every time would be quite annoying and is very much just spam. There should be some criteria at which the message should not be shown anymore. A few ideas I have:
1. The absolute first time a player ever interacts with a lockable block
2. Show the message every time until the player has entered the menu.

**Comment by hoehoetvhss** [comment]
> Do you imagine this to be a one time message when the player first interacts with a block? I think showing a message every time would be quite annoying and is very much just spam. There should be some criteria at which the message should not be shown anymore. A few ideas I have:
> 
> 1. The absolute first time a player ever interacts with a lockable block
> 2. Show the message every time until the player has entered the menu.

I think it would be good to choose this way. / It is only perceived as spamming to continue to expose messages as above.

**Comment by spnda** [comment]
This has now been added. If any more config options related to this should be added, please don't hesitate to suggest them!

**Comment by Troothe** [comment]
I think this is a useful feature, if it can be either limited or turned off/on.  As it is now, is there any way to keep the message from popping up every time an interaction is made?  It does seem to spam the chat quite a bit, so this would be a very good addition in my opinion (if it does not exist already).

I tried removing the lock_hint within the translations_en.yml file, but it then (somewhat expectedly) falls back to the "Unknown translation" fallback_string

**Comment by spnda** [comment]
> I think this is a useful feature, if it can be either limited or turned off/on.  As it is now, is there any way to keep the message from popping up every time an interaction is made?  It does seem to spam the chat quite a bit, so this would be a very good addition in my opinion (if it does not exist already).
> 
> I tried removing the lock_hint within the translations_en.yml file, but it then (somewhat expectedly) falls back to the "Unknown translation" fallback_string

This was unintended and has already been fixed by the latest commit. I'm gonna see about re-releasing 1.0.6 or 1.0.7 today.
