### ISSUE TITLE
[Bug]: Maximum number of blocks.

### ISSUE THREAD

**Issue by hoehoetvhss** [spnda/BlockProt#122]
### Version of BlockProt

BlockProt 1.0.3 / Paper-85 (1.18.1)

### Description of the bug

Setting `player max locked block count: -1` in the `Config file` does not install protected blocks.

### Steps to reproduce

1. player max locked block count: -1 Setting
2. /blockprot reload or sever reboot
3. chest place

**Comment by spnda** [comment]
Stupid mistake from me lol, thanks for reporting
