### ISSUE TITLE
[Bug]: Copy Configuration doesn't work

### ISSUE THREAD

**Issue by Kultman** [spnda/BlockProt#123]
### Version of BlockProt

1.18.1 PaperSpigot

### Description of the bug

Shift rightclick to enter UI. Set a friend and then copy configuration for a chest. Paste that configuration to other chests, only my friend can't open chests. If I set the friend list manually it works. Copying configuration has my friend in friend list, just doesn't work

### Steps to reproduce

Shift rightclick to enter UI. Set a friend and then copy configuration for a chest. Paste that configuration to other chests, only my friend can't open chests. If I set the friend list manually it works. Copying configuration has my friend in friend list, just doesn't work

**Comment by hoehoetvhss** [comment]
Is BlockProt Version 1.0.3?

**Comment by hoehoetvhss** [comment]
[https://youtu.be/TVM-GpfTass](url)

The above video is a video that I have implemented.
It works normally.

※ I don't know if I understood and copied it properly.

**Comment by spnda** [comment]
I also cannot reproduce this. I get the same results as @hoehoetvhss. Could @Kultman maybe provide a bit more context and information?

**Comment by hoehoetvhss** [comment]
@Kultman A way to help fix bugs is to shoot a video.
