### ISSUE TITLE
[Feature Request]: Public Chests, Doors and etc.

### ISSUE THREAD

**Issue by ilfarpro** [spnda/BlockProt#125]
### Feature description

Long story short, sometime some players lock public chests on server and making them private, so no one except me (server owner and him) can open them. So my feature suggestion is to add ability to make public chests, so no one can lock it. Anyone can access it. Same story with doors and other blocks. For example someone locked doors on servers spawn, lobby or on someone's home (which was unlocked by owner). 

I don't want to add plugin such a WorldGuard, because it's a huge gamechanger. I love BlockProt for being unique, simple and realistic.

**Comment by spnda** [comment]
Yeah, I think this is in fact a crucial thing that is missing. The issue I have right now is that how the system works is that if there is a player ID stored in the chest/furnace/... it is deemed locked and owned by that player. If there is no player ID, it's free to anyone.

So I'm unsure how this would be implemented in regards to the GUI, as well as the underlying code. I will definitely think about it more :D

**Comment by ilfarpro** [comment]
What if implement it thru "Add friend" button? For example Add Friend "Everyone" where you can set permissions to just look or look and pick. I think it's simple way. 
Yes chest still owned by %PlayerName% but user Everyone also has access to it if owner gave permission. Is it possible to create abstract player called "Everyone" so I can add him and manage his permissions?

**Comment by spnda** [comment]
I've added this with 1410a72: Players can now make their blocks public and change their permissions for that specific block. The implementation is very similar to what @ilfarpro suggested because it is the simplest way possible tbh.

Thanks for your suggestion!
