### ISSUE TITLE
[Bug]: Can use hopper minecart to steal items.

### ISSUE THREAD

**Issue by August7** [spnda/BlockProt#126]
### Version of BlockProt

1.0.3

### Description of the bug

Place the hopper minecart under the locked container to get the contents of the container.

### Steps to reproduce

1.Lock the chest.
2.Place rail under the chest
3.Place hopper minecart on the rail.
4.Right click hopper minecart.

**Comment by spnda** [comment]
@August7 Would it be fine if hopper minecarts continue to not be lockable? This would mean that to use hopper minecarts you'd need to disable the hopper protection for a block, which could make it potentially vulnerable. Right now, I'll just disallow the hopper moving items if the hopper protection is enabled.

If you want hopper/chest minecarts to be lockable too, please open a separate issue.
