### ISSUE TITLE
Anvils can fall and loose their protection

### ISSUE THREAD

**Issue by spnda** [spnda/BlockProt#130]
Protections for anvils are stored by location (like all other blocks). However, anvils have physics and can fall, thus invalidating their previous location. This also becomes an issue with statistics, as the location stored there is also invalidated. I see two options here:
- Change the protection to the new location (Difficult to code)
- Prohibit locked anvils from falling (More restrictive, might cost performance)

**Comment by vincentwang0905** [comment]
Should be changed to all the blocks that will fall
Because you can customize whether the block should be locked

**Comment by spnda** [comment]
I've addressed this by just cancelling any falling that happens. I previously thought this would have a great performance cost, which turned out to be optimised away by the server so it really wasn't an issue in the end.
