### ISSUE TITLE
[Question]: How do I unlock all of a player's chests?

### ISSUE THREAD

**Issue by build233** [spnda/BlockProt#132]
### Your question

Sorry，I don't understand English。：）
I am a server OP

**Comment by hoehoetvhss** [comment]
Looking at the Chest, `Shift + Right Click`

**Comment by build233** [comment]
> 看着胸膛， `Shift + Right Click`
> 
> https://www.youtube.com/watch?v=XqmNoftGj9E
> 
> 观看和关注上面的视频也可能会有所帮助

Thank you！
