### ISSUE TITLE
[Bug]:translation problem

### ISSUE THREAD

**Issue by vincentwang0905** [spnda/BlockProt#143]
### Version of BlockProt

~1.0.6

### Description of the bug

Options `language_file: translations_en.yml`

The language option has no "" (like `"translations_en.yml"`)

If you fill in the language file directly(like `language_file: translations_zh-tw.yml`)

If I use this plugin function in game
All messages will be displayed `Unknown translation`

### Steps to reproduce

1.go to config file
2.set `language_file: translations_en.yml` to `language_file: translations_zh-tw.yml`
3.join game
4.see this

**Comment by spnda** [comment]
No "Unknown translations" should be shown I think... It should fallback to the translations_en.yml, so that's still valid. The issue you're having here though is caused by the file is called `translations_zh-TW.yml`, so the name is different and it can't find it.

**Comment by spnda** [comment]
Not sure if this is entirely related, but from another issue I found 6d89dca might have fixed this issue. Could you perhaps try this build and see if the issue persists?
[blockprot-spigot-1.0.6-all.zip](https://github.com/spnda/BlockProt/files/8209057/blockprot-spigot-1.0.6-all.zip)

**Comment by vincentwang0905** [comment]
fixed 👍
