### ISSUE TITLE
[Bug]: Lock hint message being spammed in chat

### ISSUE THREAD

**Issue by cha0spixel** [spnda/BlockProt#144]
### Version of BlockProt

blockprot-spigot-1.0.6-all

### Description of the bug

Whenever you click on a door or chest, the message "You can protect your blocks by crouching and Right-clicking your chest…. Also Check out /blockprot settings to configure it to your liking.“
The message should only come once and not every time. That spams the chat quite a lot. Can you please change this? 

### Steps to reproduce

1. Go to a door 
2. Right click it
3. Message comes every time

https://user-images.githubusercontent.com/101369356/157771798-371ffbb2-05d6-4813-90c4-140792ef69a1.MOV

**Comment by spnda** [comment]
Is this a bug in the sense that it doesnt go away, even if you go into the menu? Or is this a feature request that the message should only be sent once in general?

The bug that the message never goes away should have been fixed already in the re-release of 1.0.6 as a few people reported this on Discord already but they said the re-release fixed it. If you are experiencing that the message never goes away, could you please re-download the plugin?

**Comment by cha0spixel** [comment]
yes, this one is a bug in the sense that it doesn't go away even if i go into the menu. I re-downloaded the plugin but nothing changed. every time i open a door or chest i get this message. it would be nicer if this message would only come once.

**Comment by spnda** [comment]
@cha0spixel And it really doesn't go away if you crouch and right click a block? Does the behaviour change if its a chest or furnace? Or is this only on doors?

**Comment by vincentwang0905** [comment]
Same

**Comment by spnda** [comment]
I'm so confused.... The JAR from CurseForge works perfectly fine for me, no matter how I try and test it. fecc191c6b785e46e2abeabc33e45015e158b251 should have fixed this issue entirely and people on Discord have already said using the version from GH fixed their issue. I will however implement a cooldown for the message right now.

https://user-images.githubusercontent.com/43609023/157871477-33ad9ebb-7652-4290-9e4d-a964604f85ed.mp4

**Comment by cha0spixel** [comment]
does the message come to you when you open or close a door? I downloaded the new jar from CruserForge this morning. No matter what I do, whether I kneel or stand. The message keeps coming.


I saw that your server is configured in German... do you speak German? I also speak German. maybe then it will be easier to understand.

**Comment by cha0spixel** [comment]
a cooldown would be really great.

**Comment by spnda** [comment]
@cha0spixel I've added a 10 second cooldown for the message. Would you mind trying it out? Thank you!

[blockprot-spigot-1.0.6-all.zip](https://github.com/spnda/BlockProt/files/8233096/blockprot-spigot-1.0.6-all.zip)

**Comment by cha0spixel** [comment]
okay that is of course a reason to continue writing in english. I won't be home until 8 p.m. but then I will test it immediately and then get back to you immediately. is the cooldown adjustable in the config?

**Comment by spnda** [comment]
Nope, but that's a good point I forgot to add. So.... that's being added now

**Comment by cha0spixel** [comment]
Excellent! the bug is fixed. The message only comes back after 10 seconds. As feature it would be super cool if you could set the time in the config. thank’s for your work! really cool plugin, and really good support from you. 💯👍

**Comment by cha0spixel** [comment]
Uploading 66872346138__480C7556-E0A7-41D2-AD25-59A246DEC024.MOV…

**Comment by cha0spixel** [comment]
https://user-images.githubusercontent.com/101369356/157958287-065b17bf-5b12-4a6c-9b50-f7b8c7050758.MOV

**Comment by spnda** [comment]
> Excellent! the bug is fixed. The message only comes back after 10 seconds. As feature it would be super cool if you could set the time in the config. thank’s for your work! really cool plugin, and really good support from you. 💯👍

Great! And entering the menu makes the message go away for good now? Or is that still a unsolved bug?

**Comment by cha0spixel** [comment]
Hey spnda,
when will you release the new file? :)

**Comment by spnda** [comment]
@cha0spixel Friday and Saturday I can't upload to CurseForge anyway so it will have to wait 1/2 days.
