### ISSUE TITLE
read permission can write

### ISSUE THREAD

**Issue by FakEEE14** [spnda/BlockProt#153]
### Version of BlockProt

1.0.7

### Description of the bug

hi
when you add a permission to a player it's have read and write permission by default, but when you remove write and only let the player read the player still can write in the chest

### Steps to reproduce

nothing special
sneak and right-click on a locked chest,
go to friend manage tab
add a player to friend list and tap on it to manage the player
then change the permission untill the player have read only

**Comment by spnda** [comment]
Was this some special case or some special block? The code to prevent players who don't have write access seems valid and correct, and I currently don't have a secondary Minecraft account to test this with.

**Comment by FakEEE14** [comment]
it was normal chest
