### ISSUE TITLE
[Bug]: Blockprot.admin permission dont work

### ISSUE THREAD

**Issue by Marek09** [spnda/BlockProt#166]
### Version of BlockProt

1.1.1

### Description of the bug

Hello mate! With the new update 1.1.1 the blockprot Admin permission doesnt' work. I cant open Chest as an OP on my Server. 
I got an permission plugin to manage the permission.yml and this got no errors. I think there could be a short bug in the new version of this beautiful plugin. Can u fix this fast? 
Or can i fix this by myself? 

Greetings Marek

### Steps to reproduce

1. Create a chest with an Member User
2. Login as an OP/Server Admin
3. Try to open the locked chest.

**Comment by spnda** [comment]
Hi. So I see you can't open chests from others, which is actually intended. With `blockprot.admin` (which you should have by default if you're OP) you only get the permission to view a block's information and to unlock chests, through which you can then can view their contents. So this seems to work as expected, or would you say there should be changes to this?

**Comment by Marek09** [comment]
Hey spnda, 
first of all thank u for your fast reply. I main function of this plugins works really good. The chest are save for other player, but as an admin i can only see the "Blocks information" and i cant open or unlock the chest. There is no option in the GUI. i added a screenshot i hope u can see it. I have an Minecraft 1.18.1 Server installed. 
![chest](https://user-images.githubusercontent.com/107725820/174480894-cccc194c-8c72-462c-8395-71be4a8454bc.PNG)

**Comment by spnda** [comment]
For me, if I have `blockprot.info` and `blockprot.admin`, it works just as expected and I don't see what you are seeing. If I only have `blockprot.admin`, I can't even access the menu, but that's a different issue to what you are experiencing. So, which permissions do you precisely have and are you using any integrations (Towny, Lands, WorldGuard)?

**Comment by spnda** [comment]
I just fixed that other issue I found if one has only the `blockprot.admin` permission, perhaps it fixes your issue as well? Could you please try this?
[blockprot-spigot-1.1.2-all.jar.zip](https://github.com/spnda/BlockProt/files/8935572/blockprot-spigot-1.1.2-all.jar.zip)

**Comment by Marek09** [comment]
Hey spnda,
I tested the new update and it works!! You solved the issue. I'm now able to unlock chests from other players, but if i want to lock them again (after checking the items in the chest) it is locked for myself and not the original owner. Would it be possible to lock the chests without them noticing I opened them?  (now seen in "manage friends")

**Comment by spnda** [comment]
Nope, that isn't a feature currently. ... Perhaps I could introduce some "peek into inventory" button instead of requiring to unlock every time. I think I just kept it this way to keep myself as an admin from stealing from other's chests or knowing what's in them, effectively guaranteeing some level of privacy.

**Comment by Marek09** [comment]
The "peek into inventory" is a great idea. If you are playing with friends you dont need to open all chests,  but if you are playing with foreign players it would be nice to able to look into their chests. e.g. to check for cheated items etc.

**Comment by Cappee7** [comment]
Definitely agree. As a server admin that uses this on a public server, would be great to have the ability to peek into inventories without having to unlock the block first.

**Comment by spnda** [comment]
Right, forgot about this. I have some rudimentary code for this on my old machine, so I'll try and get that and fix it up soon.

**Comment by vincentwang0905** [comment]
I thought maybe I could add a permission
Like: blockprot.adminplus
Can view player locked blocks
And this permission is not available by default (including administrators)
Need to use luckperms or other permission editor to give permission to work

Otherwise, there will be hacks to hide the modified items
and place it in a locked block
we cannot manage it effectively
Instead, it needs to be unlocked to manage

I think it's a very serious problem
has to be unlocked to check
So meaningless and no player rights(Because we can't lock on the player's behalf)

**Comment by spnda** [comment]
> The "peek into inventory" is a great idea. If you are playing with friends you dont need to open all chests, but if you are playing with foreign players it would be nice to able to look into their chests. e.g. to check for cheated items etc.

Sorry for this being so late, but this has just been added with 592b2928bc4ee1655143960493820b9d9c9d9088.
