### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Popperonii** [spnda/BlockProt#167]
### Version of BlockProt

1.1.2

### Description of the bug

When setting the `notify_op_of_updates` in config.yml to `true`, it would cause a phantom crash. No errors would be displayed and players would not be able to lock new blocks. Blocks they had created and locked before the config change however were still locked out to non-owners.

### Steps to reproduce

1. Navigate to config.yml in BlockProt plugin folder
2. Change `notify_op_of_updates` to `true`
3. reload the plugin

**Comment by spnda** [comment]
Are you using `/reload` from Bukkit/Spigot? `/reload` gives warnings that it might break plugins and I don't really support it very well. I introduced `/blockprot reload` to have a better and more controllable version of `/reload`. When I use `/blockprot reload` I don't get this 'phantom crash' you describe; everything continues working as expected.
