### ISSUE TITLE
[Bug]: Shulker despawn when broken on 1.19

### ISSUE THREAD

**Issue by Beenester** [spnda/BlockProt#171]
### Version of BlockProt

1.0.7

### Description of the bug

1.19 shulker boxes despawn when broken if anything is inside, and everything inside is then lost. reloading fixes the problem but only for one break, so if i had 3 shulker boxes with items an admin would need to reload the plugin 3 times. Also 1.19 manage friends is broken and instead becomes a way for players to duplicate maps.

### Steps to reproduce

grab a shulker box and put any amount of items inside. then break with pickaxe.

### Additional context

clip of what happens - https://medal.tv/games/minecraft/clips/udFWj7G-48dJt/d1337DqMPerm?invite=cr-MSwwVlEsODAyOTM0Nzks

**Comment by spnda** [comment]
1.0.7 doesn't support 1.19. 1.1.3 released a few days ago, try that and see if the issue still exists.
