### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by CodyMaster007** [spnda/BlockProt#182]
### Your question

How to delete spamming message when i click on chest or other lockable block?
Message is written in Russian language
![сообщение](https://user-images.githubusercontent.com/82391244/203312154-bea83c52-affa-4998-a5cb-2900fee95a5f.PNG)

**Comment by spnda** [comment]
Look at the BlockProt/lang/translations_ru.yml file and look for lock_hint: "..." and delete the contents so its just `lock_hint: ""`. The message will be gone then, however, it should also only appear until you open the menu at least once.

**Comment by CodyMaster007** [comment]
It's work, thanks for answer
