### ISSUE TITLE
[Bug]: Hopper Protection doesn't work when hopper is placed below a chest

### ISSUE THREAD

**Issue by JoeYong01** [spnda/BlockProt#185]
### Version of BlockProt

1.1.7

### Description of the bug

I notice user on my server have been abusing something, even tho hopper protection is enabled, by placing a hopper below a chest, they can steal items. 

I've tested this with my own items with a help of another player and the hopper will pull items from my protected chest

### Steps to reproduce

1. Place a chest
2. Get another player to place their hopper below the block your chest is located
3. Fill in items in the chest, witness it get pulled by the hopper
4. Or the other way round, the hopper is already there, and I place a chest

**Comment by spnda** [comment]
Is this only on 1.19.3? Or has this been happening on previous versions too?

**Comment by JoeYong01** [comment]
The server is on 1.19.2. I haven't tested on 1.19.3.

I have not confirmed whether it has been happening with previous versions, I only just found out recently.

**Comment by spnda** [comment]
Hmm, I cannot reproduce this on my Spigot 1.19.3 server. As long as hopper protection is enabled, and the hopper is not owned by the same player or if its unlocked, items will not be moved. Do you have any more context? Say Spigot, Paper, ... server?

**Comment by JoeYong01** [comment]
I'm using Purpur build 1835. I've tested locally with the latest updated version of purpur and the plugin seems to be working fine. I'll probably look into updating it into the latest version

**Comment by spnda** [comment]
Have you got any updates on this? Perhaps this was some incompatibility with another plugin that caused BlockProt to not work correctly?
