### ISSUE TITLE
[Feature]: Add limit to chest, block etc. owning

### ISSUE THREAD

**Issue by KALITRIK** [spnda/BlockProt#202]
### Feature description

In config file if we would have a limit for about owning things we can protect server many bad uses, like with our owned blocks, locking end portal's surroundings etc

**Comment by spnda** [comment]
From what I understand what you're trying to say, this has been a thing for ages. `player_max_locked_block_count` sets the maximum amount of blocks a single player can lock. With a combination of `blockprot.lockmax` and `blockprot.locklimit.10` you can change the maximum through permissions.

**Comment by KALITRIK** [comment]
Oh sorry, i am new at this plugin, thanks for reply.
