### ISSUE TITLE
[Feature]: I did a fully translations_tr.yml

### ISSUE THREAD

**Issue by KALITRIK** [spnda/BlockProt#205]
### Feature description

---
locale: tr

enabled: Aktif
disabled: Devre Dışı
inventories:
  back: Geri
  last_page: Önceki Sayfa
  next_page: Sonraki Sayfa
  block_lock: Blok Kilidi
  user_settings: Kullanıcı Ayarları
  block_info: Blok Bilgisi
  lock: Kilitle
  unlock: Kilidi Aç
  lock_on_place: Otomatik olarak kilitle
  copy_configuration: Konfigürasyonu kopyala
  paste_configuration: Konfigürasyonu yapıştır
  set_block_name: "Bloğunun ismini ayarla."
  inspect_contents: "İçindekilere bak." 
  redstone:
    settings: "Kızıltaş Ayarları"
    redstone_protection: "Kızıltaş Koruması"
    piston_protection: "Piston koruması"
    hopper_protection: "Huni Koruması"
    enable_all: "Hepsini aç"
    disable_all: "Hepsini kapat"
  friends:
    manage: Arkadaşlarını Yönet
    edit: Arkadaşı Düzenle
    remove: Arkadaşı Sil
    search: Oyuncuları Ara
    search_history: Arama geçmişi
    result: Oyuncular bulundu
    the_public: "Genel"
    the_public_desc: "Bu sunucudaki her oyuncuyu temsil eder."
    make_public: "Genel"
    permissions: "İzinler"
    permission:
      read: "+ Eşyalara Bakma Yetkisi"
      write: "+ Eşyaları Düzenleme Yetkisi"
      manager: "+ Bloğunun Her Şeyini Düzenleyebilme Yetkisi"
  statistics:
    statistics: İstatistikler
    player_statistics: Oyuncu istatistikleri
    global_statistics: Sunucu istatistikleri
    container_count: Blok sayısı
    your_blocks: Sendeki bloklar
messages:
  permission_granted: İzin verildi.
  unlocked: Kilidi açıldı.
  no_permission: İznin yok.
  friend_added: Arkadaş eklendi.
  friend_removed: Arkadaş silindi.
  friend_already_added: Arkadaş zaten ekli.
  friend_cant_be_removed: Arkadaş silinemez.
  redstone_added: Kızıltaş koruması eklendi.
  redstone_removed: Kızıltaş koruması kaldırıldı.
  exceeded_max_block_count: Kilitlenebilen maksimum blok sayısına ulaştın.
  lock_hint: >
    §6Sandıklar, fırınlar ve daha birçok bloku eğilip ve sağ tıklayarak koruyabilirsiniz!
    Aynı zamanda /blockprot yazarak kendi isteklerinize göre ayarları değiştirebilirsiniz.

integrations:
  lands:
    protect_containers_flag_name: Konteynerleri (sandık, fırın vb.) koru. (BlockProt)
    protect_containers_desc: Bir oyuncuya sandıklar, fırınlar gibi şeyleri korumaya izin verir.
    require_protect_for_friends_flag_name: Arkadaşlarınız için "Konteynerleri Koru" izni gerekmektedir. (BlockProt)
    require_protect_for_friends_desc: Yalnızca "Konteynerleri koru" etiketine sahip olan oyuncular arkadaş olarak eklenebilir.

**Comment by spnda** [comment]
We already have a fully updated Turkish translation: https://github.com/spnda/BlockProt/blob/be99d307795fb298d5f35d334c16d768e9c1b461/spigot/src/main/resources/lang/translations_tr.yml

Reminder to always use gitlocalize if you want to add a missing translations or find any issues or mistakes with the translations.

**Comment by KALITRIK** [comment]
> We already have a fully updated Turkish translation: https://github.com/spnda/BlockProt/blob/be99d307795fb298d5f35d334c16d768e9c1b461/spigot/src/main/resources/lang/translations_tr.yml
> 
> Reminder to always use gitlocalize if you want to add a missing translations or find any issues or mistakes with the translations.

the problem is this gitlocalize doing something wrong look with more attention something is missing in that default translation. Compare with english and turkish

**Comment by KALITRIK** [comment]
like lock_hint

**Comment by spnda** [comment]
gitlocalize is doing nothing wrong. You're not viewing the file itself but instead a diff, showing parts of the file that changed. Look at the file I linked earlier :). Turkish is indeed 100% covered. However, I've looked at your translations and it looks like a few differ from the current ones, so I wonder which ones are more correct or better. I'll look into it now and see if there's any need in changing anything.

**Comment by KALITRIK** [comment]
ok

**Comment by spnda** [comment]
By looking at what you changed versus what's already available and researching what the phrases mean I definitely prefer what we already have. I'm sorry but I'll have to decline your request.

**Comment by KALITRIK** [comment]
ok no problem i just thinked that default translate had some shortcomings
