### ISSUE TITLE
[Broken Feature]: Lands Integration doesn't work due to API update of Lands plugin

### ISSUE THREAD

**Issue by ilfarpro** [spnda/BlockProt#207]
### Version of BlockProt

blockprot-spigot-1.1.8-all

### Description of the bug

![image](https://user-images.githubusercontent.com/16963651/227607041-d72ca445-b5a0-4cc8-a3e6-84ea8fd031f9.png)

![image](https://user-images.githubusercontent.com/16963651/227607172-c39ac175-132f-4375-a41d-48dc2c7dbec0.png)

### Steps to reproduce

Lands version 6.28.19
BlockProt 1.1.8

**Comment by spnda** [comment]
This seems to be a trivial fix, some things just changed with 6.26. However, `LandFlag` seems to be gone, and instead I see `NaturalFlag`. The documentation says `NaturalFlag`'s are for "flags like monster spawning" or other "natural" Minecraft things. I don't feel like it fits the replacement for LandFlag. You have any ideas, since you are a user of Lands?

**Comment by spnda** [comment]
@ilfarpro Could you please use this updated version to see if it works? Slight change in their API and I'm not gonna buy the plugin just to test this.

[blockprot-spigot-1.1.8-all.zip](https://github.com/spnda/BlockProt/files/11069392/blockprot-spigot-1.1.8-all.zip)

**Comment by ilfarpro** [comment]
@spnda 

It works now.

Registered 2 flags
![image](https://user-images.githubusercontent.com/16963651/227761741-b2f0b845-d39e-4543-a1fc-43a4855546ab.png)

But there are warning about 'bp_lock_containers' flag. Despite it works, I think. Because I found it in GUI and was able to toggle.
![image](https://user-images.githubusercontent.com/16963651/227761788-3ff6f315-e2cd-4f3c-9750-5e1c64774c3a.png)

**Comment by ilfarpro** [comment]
I'm still newbie in terms of Lands plugin. There are quite many things to learn and I not fully understand everything yet.

**Comment by spnda** [comment]
Hi, sorry for the delay. However, I think I found what triggers that exception. Could you please try this version?
[blockprot-spigot-1.1.9-all.zip](https://github.com/spnda/BlockProt/files/11163996/blockprot-spigot-1.1.9-all.zip)
