### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Yaeui** [spnda/BlockProt#209]
### Your question

How do I save settings? Every time I open the chest to "the public", it locks again after someone opens it and takes stuff out. This also happens when I unlock chests, the chest always gets rid of my edits after someone uses it.

**Comment by spnda** [comment]
It should save every setting as soon as you change it. Could you please tell me what server youre running, so I could test it on my end?

Please run `/version` and at best every other related command and paste its result here, thank you.

**Comment by Yaeui** [comment]
I'm on minehut, and it's version 1.19.4.
I'm not sure what you mean by run /version, but this is what comes up when I start the server, is this part of the problem? Is this fixable or should I just wait until it gets updated?

![Screenshot 2023-03-30 110146](https://user-images.githubusercontent.com/129358277/228924633-55b36171-22ea-4f67-8c27-716c21da6c63.png)

**Comment by spnda** [comment]
This has been fixed by 61e93cb3773a97d2e4f4c3ed8f774cc3e8b92c46. Will release an update within the next few days. Thank you
