### ISSUE TITLE
[Bug]: Making doors public only interacts with half the door

### ISSUE THREAD

**Issue by Exos9** [spnda/BlockProt#214]
### Version of BlockProt

1.1.8

### Description of the bug

When a door is made public, only half of the door is public. EG, if I open the GUI for Blockprot on the top half of my door, and another user opens the door by clicking on the bottom half, the bottom half hasn't been made public.

### Steps to reproduce

1. Open the GUI on either the top or bottom half of a door
2. Lock the door
3. Make it public
4. Have another user try to open or close the door on the half of the door that wasn't used in the GUI.

### Additional context

This only happens when making a door public. This doesn't happen when adding a specific person to a block, or when running any other actions (redstone protection, etc...)

**Comment by spnda** [comment]
Does this specifically only happen with the public feature? Does the rest work?

**Comment by Exos9** [comment]
Yep, specifically with the public. Adding people manually works as intended.

**Comment by Exos9** [comment]
I'd also like to add that all other functions work (like red stone protection) as intended. Adding people by hand is fine as well
