### ISSUE TITLE
[Bug]: Chests can not be placed on public

### ISSUE THREAD

**Issue by Marek09** [spnda/BlockProt#215]
### Version of BlockProt

1.1.10

### Description of the bug

Hey guys, 

I noticed a little bug in the latest version today. If I want to change my chest always stand on "public" I can not do this. The API does not allow the change, or it happens nothing. 

Steps to reproduce:

1. /blockprot settings
2. lock automatically

Expected result:
The switch can be toggled so that by default all new chests are set to public.

Actual result:
Nothing happens, the chest stays on private and the switch does nothing. 

Thanks for the great plugin, I appreciate feedback. 

### Steps to reproduce

1. /blockprot settings
2. lock automatically

**Comment by Marek09** [comment]
![Blockprot](https://user-images.githubusercontent.com/107725820/232618784-891f826f-81b3-43f2-8062-e68a1e2a2c0b.PNG)

**Comment by spnda** [comment]
Thank you, this is fixed now. Here's a build for now until I update to 1.1.11:
[blockprot-spigot-1.1.10-all.zip](https://github.com/spnda/BlockProt/files/11286888/blockprot-spigot-1.1.10-all.zip)
