### ISSUE TITLE
[Bug]:Chest is locked but friends can open it

### ISSUE THREAD

**Issue by cow321** [spnda/BlockProt#221]
### Version of BlockProt

latest

### Description of the bug

So they cant break the chest or open it but they can crouch and right click it and unlock/lock it and change the permissions

### Steps to reproduce

place chest
lock it
friends come over
they crouch and right click
they can unlock/lock it

### Additional context

none

**Comment by spnda** [comment]
Can you please check if theres any output in the console? Any exceptions?

**Comment by cow321** [comment]
i am using 1.19.4 and noah there isnt anything related to it inside of the console
