### ISSUE TITLE
[Bug]: Chest is unlocked, but shown als locked

### ISSUE THREAD

**Issue by LeonBoettcher** [spnda/BlockProt#226]
### Version of BlockProt

1.1.11

### Description of the bug

I can see the Block in the stats, but it is not locked

### Steps to reproduce

1. Lock a chest
2. try to lock another (locked blocks limit is set to 1)
3. try to unlock the chest

**Comment by spnda** [comment]
So effectively, you're saying that in your case you unlock the block and it still shows up in the statistics window?

**Comment by LeonMonkeygamer** [comment]
Yes, the statistics window shows me a chest, when i look at the chest its unlocked.
You need to know, i set a limit of 1 locked chest a player. Now i cant set a new locked chest until set the limit to 2 or more

**Comment by LeonMonkeygamer** [comment]
Additonal information, if i now try to lock the chest, which is shown as logged (or any other) i click on lock and then the menu closes without a chat message (like Max Lock limit reached), so i was confused
