### ISSUE TITLE
[Question]: Can't add chiseled_bookshelf in `lockable_tile_entities`

### ISSUE THREAD

**Issue by ravel10** [spnda/BlockProt#231]
### Your question

When i add chiseled_bookshelf in `lockable_tile_entities`
i have "[BlockProt] Caught invalid value passed to lockable_tile_entities: CHISELED_BOOKSHELF" in the console

I have the same message with COMPOSTER

![image](https://github.com/spnda/BlockProt/assets/36196418/16d76162-ad5b-4c30-a50e-36f9f811a805))

It's normal ?

**Comment by spnda** [comment]
`Composter` is not a tile entity and can therefore not be locked as a tile entity.

`Chiseled Bookshelf` is a new tile entity from 1.20 which I will add support for now.

Thanks for mentioning this.
