### ISSUE TITLE
[Bug]: Sign not lockable_blocks

### ISSUE THREAD

**Issue by ravel10** [spnda/BlockProt#232]
### Version of BlockProt

1.1.12, Pufferfish 1.20.1 #17

### Description of the bug

![image](https://github.com/spnda/BlockProt/assets/36196418/702b5c98-eb86-4a7a-8479-c2c75841da6c)

### Steps to reproduce

1. Add Some sign in lockable_blocks
2. Reload the plugin

**Comment by spnda** [comment]
Signs are tile entities, not blocks. Perhaps you could also address that in #233? Look at DefaultConfig line 78 and 79 and extend that list.

To be honest, I'm not sure if thats even necessary or if one sign could be enough. The plugin could automatically add the wall and hanging alternatives when the normal sign is included, but perhaps that should just be up to the server admin.
