### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DawnStorm2** [spnda/BlockProt#234]
### Version of BlockProt

1.1.11. Paper 1.20.1

### Description of the bug

Lockable Shulkers are deleted when broken. When we break a shulker that can be locked, it vanishes. This doesn't happen to shulkers that can't be locked.

Our current solution is to remove skulkers from being able to be locked. We hope this can be fixed.

So far we are able to retrieve lost boxes via a different plugin. (Core protect)

### Steps to reproduce

Place shulker and put items in or simply open a close box. 
Then break it. 
It should then vanish.

**Comment by spnda** [comment]
Have you got any errors in the console? Have you got any further information about the configuration or anything that you think might affect this?
