### ISSUE TITLE
[Bug]: Lectern

### ISSUE THREAD

**Issue by ravel10** [spnda/BlockProt#235]
### Version of BlockProt

1.1.12, Pufferfish 1.20.1 #17

### Description of the bug

When add a player with only read permission, he still can take the book on lectern.

### Steps to reproduce

1. Place a Lectern
2. Add a player
3. Change permission to read only
4. Place a book on lectern
5. The added player can take the book off the lectern, but can't replace on it.

**Comment by spnda** [comment]
Hi, thanks for the report.

Could you please test the following build of the plugin? I've added a handler to check when any book is taken from a lectern, theoretically fixing the issue. I still want to have it be tested on an actual server.
[blockprot-spigot-1.1.12-all.zip](https://github.com/spnda/BlockProt/files/12137327/blockprot-spigot-1.1.12-all.zip)

Thanks.

**Comment by ravel10** [comment]
Hi, It seems to work. (i only test the lectern)
I've just noticed that player with only read permission can put books on the lectern. ^^'
