### ISSUE TITLE
[Bug]: Not working hopper protecting

### ISSUE THREAD

**Issue by razenxc** [spnda/BlockProt#240]
### Version of BlockProt

v1.1.13 - Spigot Plugin

### Description of the bug

Hello, today I discovered that players have found a way to steal things through hopper, the problem is that even if the protection against craters is turned on, things go into the hopper. Same with the hopper in the minecart.
*this happened on v1.1.12 but the protection doesn’t work on the v1.1.13 too

### Steps to reproduce

1. put the chest on the ground
2. place the hopper under the chest
3. things go to the hopper and we can pick them up

### Additional context

If necessary I can record it on video.

**Comment by razenxc** [comment]
I understood why this happens, it’s all because locking hoppers is disabled on my server, and in the listener for the hopper there is a condition that the hopper must be in the config. It turns out that in order for everything to work as I need, all I need to do is remove it from the condition `BlockProt.getDefaultConfig().isLockable(Material.HOPPER)` in listeners/HopperEventListener.java. Close it if that's what you intended.
But while I was solving this problem, I found another one, I’ll make separate problems if I can’t solve it.

**Comment by spnda** [comment]
Yeah, I guess that condition is not really sensible. You can open a PR about that or I'll just quickly push a tiny commit that fixes it.
