### ISSUE TITLE
[Bug]: Can get Player Head

### ISSUE THREAD

**Issue by ravel10** [spnda/BlockProt#250]
### Version of BlockProt

1.1.13, git-Pufferfish-27

### Description of the bug

Player can get player head after searching a player name

### Steps to reproduce

1. Shift Right Click
2. Manage Friends
3. Search Players
4. Enter a player name
5. Click on player head
You can get the head of players found  and the glass pane named "Back"

**Comment by ravel10** [comment]
I retested with the modrinth jar and it seems that there is no longer the problem on the gui after the Search Players.
But now when i make public a lock, i can get the head named "The public" and i have this error on the console
![image](https://github.com/spnda/BlockProt/assets/36196418/a5ca7bfb-d675-4eda-b04e-723800b974a2)
(Version 1.1.13, git-Pufferfish-33)

**Comment by spnda** [comment]
Pretty sure I fixed this with 419b357071b728850f6e663ab9fd0e50054da3a0 a long time ago. Sorry for the late response.
