### ISSUE TITLE
[Bug]:  Cant Copy and paste settings from one to another chest

### ISSUE THREAD

**Issue by CptGummiball** [spnda/BlockProt#256]
### Version of BlockProt

1.1.13

### Description of the bug

We can no longer copy the configuration of the boxes on our server and apply it to other boxes.

The console gives no errors.

Our plugin list:

### Steps to reproduce

1. Open BlockProt Menu at Chest 1
2. Click copy config
3. Click apply config (an then nothing happens)

### Additional context

Our plugin list:

Paper Plugins:
BKCommonLib, ExtraDatabasesH2, Minepacks, TicketManager
 Bukkit Plugins:
AntiPopup, AxGraves, AxShulkers, AxSmithing, BeautyQuests, BlockEffects, BlockProt, BoomBox, Celebrate, ChristmasPlus,
Chunky, ChunkyBorder, Citizens, CitizensGUI, ClickHarvest, ColoredAnvils, CommandButtons, CoreProtect, CustomCommands, DataPackLoader
Denizen, Disenchantment, DropEdit2, EmployMe, EntityClearer, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn, FancyHolograms,
FarmControl, GCore, GSit, HarderDespawn, HsRails, Item-Chest-Sorter, ItemSoulBind, Lands, LibsDisguises, LuckPerms
Maintenance, MiniMOTD, MTDeathLocator, Multiverse-Core, Multiverse-Portals, NoteBlockAPI, Pl3xMap, Pl3xMap-Banners, Pl3xMap-Claims, PlaceholderAPI, PlayerStats, PostOffice, ProtocolLib, Skulls, spark, StreamingDrops, TAB, TCDestinations, TeaksTweaks, Tether, TheDragon, TimeIsMoney, Train_Carts, TreeFeller, UberEnchant, UltimateAutoRestart, UltimateCaves, Vault, ViaBackwards, ViaVersion, VillagerFollow, VillagerMarket, voicechat, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuard, TabCompletion, YamipaPlugin

**Comment by CptGummiball** [comment]
Hi, I wanted to ask if there is any further information here. Even after an update to 1.1.14 nothing changed.

**Comment by TheDiscordian** [comment]
Hi! I can't seem to reproduce your issue. To confirm your reproduction steps:

1. Open BlockProt Menu at Chest 1
2. Click "Copy configuration"
3. Open BlockProt Menu at Chest 2
4. Click "Paste configuration"

Specifically what I see, is all *new* friends are added to the block (old ones are not removed).

Can you possibly give more details as to what's happening? Is *nothing* changing at all on Chest 2?

Here are my plugins, we have some overlap, but you have quite a bit more than me:

```
> plugins
[19:18:09 INFO]: Server Plugins (26):
[19:18:09 INFO]: Paper Plugins:
[19:18:09 INFO]:  - EconomyShopGUI
[19:18:09 INFO]: Bukkit Plugins:
[19:18:09 INFO]:  - AdvancedPortals, BlockProt, CMILib, CoreProtect, DecentHolograms, Essentials, EssentialsChat, FastChunkPregenerator, Geyser-Spigot, Jobs
[19:18:09 INFO]:  Lands, LifeStolen, LoginSecurity, LuckPerms, OfflineManager, PlaceholderAPI, PlugManX, ProtocolLib, Shopkeepers, SkinsRestorer
[19:18:09 INFO]:  TAB, Vault, WildRegeneration, WorldEdit, WorldGuard
```
