### ISSUE TITLE
[Bug]: Cant Move any Items in locked containers as admin (op)

### ISSUE THREAD

**Issue by CptGummiball** [spnda/BlockProt#272]
### Version of BlockProt

1.1.14

### Description of the bug

If you, as an operator, open a locked box and want to move items, they simply disappear and the chest GUI closes.

### Steps to reproduce

1. Open locked chest as op
2. move any item
3. item is lost

**Comment by spnda** [comment]
Are there any errors in the console? Also, is this the "Inspect contents" view or just opening any chest? Because with the inspect contents feature it doesn't allow you to move items directly.

**Comment by CptGummiball** [comment]
Its working now, don't know what was the problem here. I will look later for the logs. If i find something i will post it here.
