### ISSUE TITLE
[Bug]: Shulker box items are deleted after breaking the block

### ISSUE THREAD

**Issue by ianfreebern** [spnda/BlockProt#280]
### Version of BlockProt

1.1.15

### Description of the bug

When a shulker box is locked with items already in it, and it is broken, the items are gone and the shulker box is empty 

### Steps to reproduce

1. place down a new shulker box
2. place items into it
3. exit the chest ui
4. lock the shulker box
5. destroy it
6. no items are in it

**Comment by spnda** [comment]
Yes I already know about this, forgot to pull the plugin versions from CurseForge etc.
I have a partial fix locally but 1.20.6 is making it hard so I don't know what the best course of action is here, sorry.

**Comment by spnda** [comment]
This was fixed a few days ago by a2cbf5875d0704c047484ab3ab9de33e7641dcd5.

**Comment by ianfreebern** [comment]
Ok thank you
