### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RitchTempest** [spnda/BlockProt#290]
### Version of BlockProt

1.21

### Description of the bug

Not working.

### Steps to reproduce

I uses BlockProt plugins for locked chest on my Minecraft server but my friends can't uses my locked chest in 1.21

Adding friends to the chest is broken..

Please creator help me.

**Comment by spnda** [comment]
1. So you have already added those friends to those chests, yes?

2. Are you sure you didn't just add them to the personal settings (`/bp settings`)? Those settings are only defaults, that are set on blocks you place *after* changing it there. It does not affect currently locked blocks.

3. Do those friends have the correct permissions (e.g. `blockprot.lock`)?
