### ISSUE TITLE
[Bug]: problem with chests regarding hoppers

### ISSUE THREAD

**Issue by DTsumun** [spnda/BlockProt#293]
### Version of BlockProt

the last one 

### Description of the bug

Good morning !
I have a quick question why when you lock a chest but place a hopper underneath the items still fall out?

### Steps to reproduce

1- we place a container and lock it 
2- we place a hopper underneath 
3-we place an item in the trunk

**Comment by Jaster-Master** [comment]
I just tested it in 1.21 and if you unlock the hopper underneath the chest, the items do not fall out. So its not a problem. The hopper only takes the items if its locked like the chest. Or if the chest is unlocked.

**Comment by spnda** [comment]
Correct. Items will only leave the chest if
(1) both are unlocked
(2) the chest is locked but hopper protection is disabled
(3) both blocks are locked and owned by the same player
