### ISSUE TITLE
[Bug]:  Search players doesnt work

### ISSUE THREAD

**Issue by Nco3718** [spnda/BlockProt#297]
### Version of BlockProt

1.21

### Description of the bug

when i click on the "Search Players" paper, it just picks it up instead of opening a new window

### Steps to reproduce

Go to the Block Lock Menu, Click on manage friends and click on the search players paper

**Comment by spnda** [comment]
This is a bug in Spigot, for which a workaround has been found from the AnvilGUI team and I'll need to publish an update soon.
