### ISSUE TITLE
[Bug]: 1.21.3 not supported properly

### ISSUE THREAD

**Issue by Mart-y-McFly** [spnda/BlockProt#323]
### Version of BlockProt

blockprot-spigot-1.2.2-all

### Description of the bug

[NBTAPI] [NBTAPI] This Server-Version(1.21.3-R0.1-SNAPSHOT) is not supported by this NBT-API Version(2.13.2-SNAPSHOT) located in BlockProt. The NBT-API will try to work as good as it can! Some functions may not work!

### Steps to reproduce

You can update 1.21.3 (paper) and try to use the plug-in

**Comment by spnda** [comment]
Already "fixed" a few weeks ago but not published yet.
