### ISSUE TITLE
You can get Player Heads and other items

### ISSUE THREAD

**Issue by Palrex** [spnda/BlockProt#50]
If you shift+RMB on a locked block, Let's say a furnace. You can get another free furnace (multiple times) :
(Edit: It happens when you want to Lock OR Unlock any Block)

![image](https://user-images.githubusercontent.com/55802535/123550033-c4504700-d76b-11eb-8111-0c442ce704fc.png)
![image](https://user-images.githubusercontent.com/55802535/123550040-d03c0900-d76b-11eb-880b-c7a4567d5afe.png)

The same happens with Player Heads. If you search for players to add to your "friends list", you can get their heads as well. It seems to only happen on the "search screen"

**Comment by spnda** [comment]
Hello @Palrex, could you please check if there was any error or stacktrace shown in your console?
Otherwise, what version of the plugin, Minecraft version and spigot version are you on?

**Comment by Palrex** [comment]
Everytime it happens, the console shows this error:

![image](https://user-images.githubusercontent.com/55802535/123557243-1d31d680-d790-11eb-8374-b428a380ac26.png)

For the versions:

![image](https://user-images.githubusercontent.com/55802535/123557279-4e120b80-d790-11eb-9070-1c59c2c9c1e3.png)

**Comment by spnda** [comment]
Thank you.
However, right now, we **do not** support CraftBukkit servers. I would very much recommend you use Spigot or Paper instead, your other plugins will work just fine with them too.

**Comment by kacperleague9** [comment]
@Palrex cb died in 2014 cmon...
