### ISSUE TITLE
[Bug]: Wall signs

### ISSUE THREAD

**Issue by wuuthradd** [spnda/BlockProt#53]
### Version of BlockProt

0.4.1

### Description of the bug

When you add signs and wall signs to config, you can lock normal signs in blockprot GUI, but wall signs lock option are unavailable. 
![2021-07-05_21 04 42](https://user-images.githubusercontent.com/57961072/124506692-df0e6580-ddd4-11eb-92b6-e45ee0b1746a.png)
![Screenshot_3](https://user-images.githubusercontent.com/57961072/124506860-3280b380-ddd5-11eb-85ed-d965f421f4f9.png)

### Steps to reproduce

add wall sign to block lock section of config
place wall sign and access to blockprot GUI

**Comment by spnda** [comment]
Hi, thanks for your report. This has been fixed and will be included in 0.4.2. You can get temporary builds through [Run #111](https://github.com/spnda/BlockProt/actions/runs/1005155027).
