### ISSUE TITLE
[Bug]: Map dupe using the blockProt GUI

### ISSUE THREAD

**Issue by Maccysundae** [spnda/BlockProt#54]
### Version of BlockProt

0.4.1 | paper-1.16.5-779

### Description of the bug

I dont really know how to describe it, but I hope this video from my friend helps. 
[https://youtu.be/7PrOHRT47m0](url)

### Steps to reproduce

1. Go to a blockProt protected container.
2. Go to manage friends
3. Take the map and click it out of the inventory menu
4. Exit and re-enter manage friends
5. take the map and put it in your inventory

### Additional context

not 100% sure of the paper version as the server is run on a host which just says "1.16.5 Paper" so me and the servers owner assume it's the latest version.

**Comment by spnda** [comment]
Hi, as I cannot reproduce this issue, could you please check if there are any errors/exceptions in the server console and please send them here (or over https://pastebin.com)?

**Comment by Maccysundae** [comment]
If this helps at all, the server is also running deathchests ( [https://www.curseforge.com/minecraft/bukkit-plugins/dead-chest](url) ) and the vivecraft spigot extension. 

Server logs:
[https://pastebin.com/gW4iXx9B](url)

**Comment by spnda** [comment]
Hi, thanks for your server logs. From them I see that you are running Java 8. This seems to be a issue from one of the dependencies, where I just opened an issue for this (https://github.com/WesJD/AnvilGUI/issues/157). In the meantime, I'd recommend upgrading to Java 16 (for example from [here](https://jdk.java.net/16/)).

**Comment by Maccysundae** [comment]
Thanks for the reply! 
Upgrading the server to Java 16 appears to have stopped the duplication glitch.

**Comment by shouxd** [comment]
Hi, the same happens to me but with skull heads when I add someone in Manage Friends. I can take them infinetly and put them into my inv. Im using Java 16
[latest.log](https://github.com/spnda/BlockProt/files/6776646/latest.log)
thats my log

**Comment by spnda** [comment]
> Hi, the same happens to me but with skull heads when I add someone in Manage Friends. I can take them out and put them into my inv infinetly . Im using Java 16
> [latest.log](https://github.com/spnda/BlockProt/files/6776646/latest.log)
> thats my log

Hi, I'm not sure where this issue is coming from and I would like to know more information. However I'd prefer if you would open a separate issue, as these two issues are not related.

**Comment by spnda** [comment]
@shouxd I would've preferred if you open a separate issue, however I've possibly fixed it through 0f43f8e and 06c69a9. Please download 0.4.3 from SpigotMC or GitHub, and please open a new issue if you keep experiencing it.
