### ISSUE TITLE
[Bug]: Form 0.4.6 to 0.4.7 all Chest lock for owner chest 

### ISSUE THREAD

**Issue by JustKing009** [spnda/BlockProt#60]
### Version of BlockProt

paper-1.17.1-130 and blockprot 0.4.7

### Description of the bug

_Sry my English is not so good , but i have a video for this bug._

If I update the plugin from 0.4.6 to 0.4.7, no user has any more rights to his box or to new boxes. No error message is displayed in the console. In-game only the message "No authorization" comes, regardless of whether or not with an OP. 

[https://www.youtube.com/watch?v=wHB-1C0aKgM](url) Bug Report Video

### Steps to reproduce

1. Starting Server with BlockProt 0.4.6
2. Stop
3. Starting Server with BlockProt 0.4.7
4. and you have this bug.
If you go back to 0.4.6, the users have the right to their boxes again.

**Comment by spnda** [comment]
Hi, thanks for your report. Could it be, that you have given yourself the `blockprot.bypass` permission?

**Comment by JustKing009** [comment]
yes, i have me to set op (*) premission.

**Comment by JustKing009** [comment]
thx, is fix it
