### ISSUE TITLE
[Bug]: No permission when unlocked if there is a friend added

### ISSUE THREAD

**Issue by JakeWags** [spnda/BlockProt#65]
### Version of BlockProt

0.4.8, Paper 1.17.1 

### Description of the bug

Config: Default
Plugin Version: 0.4.8
Minecraft version: 1.17.1
Server: Paper 1.17.1
Spigot: v1_17_R1

EXPECTED BEHAVIOR: After unlocking an item, regardless of the settings, the item should be accessible by all.

ISSUE: After adding a friend to any lockable item, once unlocked, nobody except that friend or friends has permissions to interact with the block. This includes breaking, opening, closing, or any interaction. The people added as friends, however, are able to interact with the block, but not break it or lock it. The owner of the block can lock it to regain permissions and the ability to break and interact with the block.

When no friends are added, the lock/unlock mechanism works totally fine.

### Steps to reproduce

1. Place and lock any lockable item.
2. Add a friend to the item
3. Unlock the item
4. Try to interact with it
5. Have friend interact with it
6. Re-lock said item and remove friend
7. Unlock item
8. Try to interact with it (it should work fine)

### Additional context

Both friends I tested this with had the same experience when they were added to my /blockprot settings friends and when they were not on the list. The bug still occurred exactly as described above.

**Comment by JakeWags** [comment]
Let me know if you want a screen recording or screenshots. It should be easy enough to replicate.

**Comment by spnda** [comment]
Hi @JakeWags, thank you for your report. It was an easy fix and will be part of 0.4.9, for now, you can use [this version](https://github.com/spnda/BlockProt/files/6887824/BlockProt-0.4.8-master-all.zip).
