### ISSUE TITLE
[Bug]: Can not double chest place

### ISSUE THREAD

**Issue by JustKing009** [spnda/BlockProt#66]
### Version of BlockProt

paper-1.17.1-137 and blockprot 0.4.8

### Description of the bug

User can only place single boxes, if you try to place a double box, it will be dropped.

Bug Report Video [https://youtu.be/9hPzh7RcGTU](url)

### Steps to reproduce

1. Place chest
2. to double chest
and finish

**Comment by spnda** [comment]
Hi @JustKing009, thanks for the report. Stupid logic error that I introduced last update. Fixed it and will come to the next update soon!

**Comment by JustKing009** [comment]
Thx! @spnda
