### ISSUE TITLE
[Bug]: Friendslist not automatic in .... doors ,

### ISSUE THREAD

**Issue by JustKing009** [spnda/BlockProt#69]
### Version of BlockProt

paper-1.17.1-165 and blockprot 0.4.10

### Description of the bug

/blockprot settings friends not working , set not automatic in chest and etc. 

### Steps to reproduce

1. use /blockpro settings
2. add friends
3. place block 
4. friend is not in block  friendslist

**Comment by spnda** [comment]
I'm sorry. I cannot reproduce this issue. Could you maybe upload a clip of you showing how the friends are not applied?

https://user-images.githubusercontent.com/43609023/128642230-0234821e-d140-4082-9322-14ebf5450a6b.mp4

**Comment by JustKing009** [comment]
[File is to big for github :/](https://youtu.be/rnrKMw_OF5U )

**Comment by JustKing009** [comment]
shulker_box is not working with 0.4.11 ...

**Comment by spnda** [comment]
@JustKing009 The shulker boxes have an interesting mechanic. As they retain their content when broken, they also keep the friends you had earlier. Meaning if you have added 2 friends to your shulker box, break it and then place it again, those friends should be copied over to the newly placed shulker box, completely ignoring the default friends.

**Comment by JustKing009** [comment]
oh ok ... awesome... its work 👍 .
