### ISSUE TITLE
[Bug]: dupe a shulker box

### ISSUE THREAD

**Issue by taka1945** [spnda/BlockProt#74]
### Version of BlockProt

BlockProt 0.4.12 , Server 1.17.1  and GriefPrevention

### Description of the bug

dupe a shulker box bug.

### Steps to reproduce

Please check yt movie.
https://youtu.be/yECXhwp51t8

A player using GP places a box on his territory.
Lock the box and then unlock it.
Other players can copy a box by destroying it against it

**Comment by spnda** [comment]
Hi @taka1945, the video really helped me a lot, thanks for that.
Could you please check the attached `.zip` file [here](https://github.com/spnda/BlockProt/pull/75) and see if that fixes your issue?
