### ISSUE TITLE
[Bug]: search_history translation BUG

### ISSUE THREAD

**Issue by vincentwang0905** [spnda/BlockProt#78]
### Version of BlockProt

0.4.13

### Description of the bug

**Search_history** cannot be added to the translated text
The server cannot read the TW translated text
If I join Search_history it will cause an error

### Steps to reproduce

1.Go to TW to translate text
2.Added search_history translation
3.Then turn on the server

Then he cannot read the TW translated text
Will automatically switch to English text

**Comment by vincentwang0905** [comment]
OK 
I'm testing
And then return it to you

**Comment by vincentwang0905** [comment]
![image](https://user-images.githubusercontent.com/76867533/131253183-fa3cbf87-4dd0-4696-b285-f0a79c9e0169.png)

**Comment by spnda** [comment]
That's a error from Spigot, failing to parse the .yml file. There's some issue with the 4 spaces (or a single tab) in front of the `search_history:` text. It seems maybe your editor added a `\t` in front of it which spigot doesn't like.
