### ISSUE TITLE
[Bug]OR[Feature]?:OP Can't open block

### ISSUE THREAD

**Issue by vincentwang0905** [spnda/BlockProt#79]
### Version of BlockProt

0.4.13

### Description of the bug

OP Can't open block

### Steps to reproduce

1.lock block
2.op Can't open  this block

**Comment by spnda** [comment]
Does this player just have OP or do they have any other permissions (maybe some removed, even)?
By default, a OP player should get the `blockprot.info` permission, which allows them to see who owns a block and which players they have added. To open a block that is not theirs, they additionally need the `blockprot.admin` permission.

Or are you referring to a OPs own blocks?

**Comment by vincentwang0905** [comment]
hmmmm
If the player is locked, it cannot be opened even if the OP has permission.
and op is locked but cannot be opened originally
sorry my en not good QQ

**Comment by spnda** [comment]
> hmmmm
> If the player is locked, it cannot be opened even if the OP has permission.
> and op is locked but cannot be opened originally
> sorry my en not good QQ

No worries. I don't quite understand you, but you could try using a translator, like https://translate.google.com. Probably the best would be to send a video over.

On your issue, I think you might not have the correct permissions set. A player needs `blockprot.admin` (player can unlock other player's blocks) or `blockprot.bypass` (player can access any block). Just being a OP doesn't automatically give you these rights, you'll have to use a permission manager to add those. See the LuckPerms plugin for example.

**Comment by vincentwang0905** [comment]
I have tried many times
Still not working
Permission plugin used: **mypermissions**

**Comment by vincentwang0905** [comment]
mypermissions ---> Does not seem to support
LuckPerms ---> **very nice!**

**Comment by spnda** [comment]
Might wanna report the issue to mypermission's author then. I'll close this issue.
