### ISSUE TITLE
[Bug]: Hoppers cannot retrieve items from unlocked containers.

### ISSUE THREAD

**Issue by konocubed** [spnda/BlockProt#89]
### Version of BlockProt

0.4.13 and 1.0.0 Beta

### Description of the bug

Hoppers cannot retrieve items from unlocked containers, i.e. chests, furnaces, smokers.

Hoppers can only retrieve items from containers if the container is **locked** and has **hopper protection** disabled. Locking a container, disabling hopper protection, and then unlocking it does not fix the issue.

### Steps to reproduce

1. Place a hopper between two chests vertically (chest feeds into hopper, hopper feeds into chest).
2. Ensure all blocks are unlocked.
3. Place items in topmost chest.
4. Observe that the hopper does not retrieve items from topmost chest.
5. Lock topmost chest and disable hopper protection.
6. Observe that the hopper can now retrieve items from the topmost chest and deposit them in the lower chest.

**Comment by spnda** [comment]
Thanks for the report. This will be part of the 1.0.0 release very soon :D
