### ISSUE TITLE
[Feature]: Worldguard region blacklist

### ISSUE THREAD

**Issue by supermem99** [spnda/BlockProt#91]
### Feature description

Hey, 
It will be cool if you can add a worldguard support. Some regions player shouldnt lock open containers. Example a global chest. And if you were able to open a global useable chest, you can lock it. Thats bad.
Solution: Add region blacklist.

**Comment by spnda** [comment]
Hi, sorry for the late response.
How would you imagine a player setting this? Should it be some flag, should the plot/area not be owned by anyone? This could be solved in many different ways. I personally don't use WorldGuard so my knowledge on how it works is pretty limited, I'd love to hear some more details from you/others about how this could be solved.

**Comment by hoehoetvhss** [comment]
I want to help a little, but I wonder if there should be a link between the World Guard and the BlockProt plugin.

It can be helpful to explain what functions are needed.

**Comment by hoehoetvhss** [comment]
To lock in BlockProt, you need the permission of !blockprot.lock!

Luckperms plugin supports a plug-in called Luckperms Extra Context to make it compatible with WorldGaurd plugin.

Then, there is a way to remove blockpror.look from the privileges of users belonging to a special group when they enter a certain area using this.

**Comment by hoehoetvhss** [comment]
However, since this is very annoying, it is my opinion to add a box lockable function through the GUI in BlockProt.

**Comment by hoehoetvhss** [comment]
Below is the `Luckperms Extra Context Plugin` website I mentioned earlier.

https://github.com/LuckPerms/ExtraContexts

**Comment by supermem99** [comment]
In my Opinion there are two good options.
1. You should be able to add a flag to a region. Like "use blockprot"
2. Add Regions in config for Blacklisting Regions and Worlds

**Comment by supermem99** [comment]
@spnda I tested it. i cant open chests with denying the flag

**Comment by spnda** [comment]
> @spnda I tested it. i cant open chests with denying the flag

So it's working as expected? Perfect, I'll push this soon then. Btw, I'm planning on releasing 1.0.0 as soon as 1.18 releases.

**Comment by hoehoetvhss** [comment]
I tested it, too. It works well as I thought, and there seems to be nothing to modify.

**Comment by supermem99** [comment]
No it doesnt work. I cannot open any Chest, if the flag is set to "deny". It tells me, that i havent permission

**Comment by hoehoetvhss** [comment]
> No it doesnt work. I cannot open any Chest, if the flag is set to "deny". It tells me, that i havent permission

I should test it again.

**Comment by spnda** [comment]
> No it doesnt work. I cannot open any Chest, if the flag is set to "deny". It tells me, that i havent permission. Im operator with *

And if it's on "allow", it works fine? I'll see if I can fix that though, thanks for testing it :D

**Comment by hoehoetvhss** [comment]
https://youtu.be/sr9xCcaZvDQ

`The link above is the video I tested.`

**Comment by spnda** [comment]
I hope this will fix the problem. Please test it, thank you :D

[blockprot-spigot-1.0.0-beta.3-worldguard-all.zip](https://github.com/spnda/BlockProt/files/7604252/blockprot-spigot-1.0.0-beta.3-worldguard-all.zip)

**Comment by supermem99** [comment]
it works thanks

**Comment by hoehoetvhss** [comment]
https://youtu.be/e3bQTeb3cYs

`The link above is the video I tested.`

I don't know if I set it wrong, but it works as below.

Allow: Open
Deny: Open

**Comment by spnda** [comment]
So, I figured out how use WG and WE and I did some more testing and everything seems to work fine. I will update the PR soon and close this issue. Thanks for testing it.

**Comment by hoehoetvhss** [comment]
> 그래서 WG와 WE를 사용하는 방법을 알아냈고 더 많은 테스트를 수행했고 모든 것이 잘 작동하는 것 같습니다. 곧 PR을 업데이트하고 이 문제를 종료하겠습니다. 테스트해 주셔서 감사합니다.

Thank you for introducing a new system.
