### ISSUE TITLE
[Bug]: This problem occurs when the block compartment has two compartments.

### ISSUE THREAD

**Issue by hoehoetvhss** [spnda/BlockProt#92]
### Version of BlockProt

git-Paper-332 / 0.4.13

### Description of the bug

In the video above, large boxes are classified and processed like each block, not one security.

Similar to large boxes, doors that occupy two compartments cause this problem.

### Steps to reproduce

https://youtu.be/kPnGTcFqC98

**Comment by spnda** [comment]
@hoehoetvhss It's not a plugins fault. It's a bug with Paper that has just been fixed and is soon available on https://papermc.io/downloads as build 335.
