### ISSUE TITLE
[Suggestion]: Additional friend system improvement.

### ISSUE THREAD

**Issue by hoehoetvhss** [spnda/BlockProt#94]
### Feature description

For blocks that have already been set up as friends, it was a little inconvenient to modify friends individually when modifying many blocks.

It may not be possible, but can you add a function that allows you to apply friend settings to blocks near the player when setting up friends?

**Comment by spnda** [comment]
I've just tested a concept of this feature.
There is a new copy button and a new paste button. The paste button only shows if there is something copied already (restarts discard any copied information, I don't think it's worth implementing this).

It copies and pastes the whole configuration, including the Redstone settings, friends and all of their permissions.
![image](https://user-images.githubusercontent.com/43609023/139910749-658255d5-c7d4-431d-9275-604b54f79f48.png)
![image](https://user-images.githubusercontent.com/43609023/139910815-db370af7-92ab-4052-b05e-5b9042441a1c.png)

Would this be a fitting solution?

**Comment by hoehoetvhss** [comment]
I think it's really good.

**Comment by spnda** [comment]
This should be fixed now and will be part of 1.0.0 :D
