### ISSUE TITLE
[Bug]: Manage Friends Not Open Bug

### ISSUE THREAD

**Issue by hoehoetvhss** [spnda/BlockProt#95]
### Version of BlockProt

Plugin Version: 1.0.0 Beta 2 / Server Version: git-Paper 336

### Description of the bug

https://youtu.be/qJmwnZ7eXAc

### Steps to reproduce

1. Shift + Right click.
2. Click Manage Friends.

**Comment by spnda** [comment]
There must be some exception thrown that should show up in the console. Could you please check your server's console and paste whatever shows up there? Thanks.

**Comment by spnda** [comment]
Thanks for the report, a fixed build is available here
[blockprot-spigot-1.0.0-beta.2-all.zip](https://github.com/spnda/BlockProt/files/7378736/blockprot-spigot-1.0.0-beta.2-all.zip)
:
