### ISSUE TITLE
[Bug]: door debug info in console

### ISSUE THREAD

**Issue by CaszGamerMD** [spnda/BlockProt#98]
### Version of BlockProt

0.4.13 \ 1.17.1 paper

### Description of the bug

on door placement
console says the item name, then "Applying to other door!"

### Steps to reproduce

place a door
look at console

**Comment by spnda** [comment]
Thanks, those were just leftover from debugging. You can get a fixed build here:
[blockprot-spigot-1.0.0-beta.2-all.zip](https://github.com/spnda/BlockProt/files/7448504/blockprot-spigot-1.0.0-beta.2-all.zip)
.
